-- Conteudo aula 17/09/2024

DECLARE
-- VARIAVEIS

V_RESULTADO VARCHAR2(1000);

BEGIN
  V_RESULTADO := 'Meus amigos'; -- atribuicao
  DBMS_OUTPUT.PUT_LINE('Bom dia!' || ' ' || V_RESULTADO || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS'));

END;

---

DECLARE
-- VARIAVEIS
V_RESULTADO VARCHAR2(1000);

CURSOR C_AREAS_ATUACOES(C_ID_AREA_ATUACAO INTEGER) IS
SELECT nome_atuacao
FROM TT_AREAS_ATUACOES
WHERE id_area_atuacao = C_ID_AREA_ATUACAO;

BEGIN
  V_RESULTADO := 'Meus amigos'; -- atribuicao
  
  DBMS_OUTPUT.PUT_LINE('Bom dia!' || ' ' || V_RESULTADO || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS'));

END;

----

DECLARE
-- VARIAVEIS
V_RESULTADO VARCHAR2(1000);

CURSOR C_AREAS_ATUACOES(C_ID_AREA_ATUACAO INTEGER) IS
SELECT nome_atuacao
FROM TT_AREAS_ATUACOES
WHERE id_area_atuacao = C_ID_AREA_ATUACAO;

BEGIN
  V_RESULTADO := 'Meus amigos'; -- atribuicao
  
  DBMS_OUTPUT.PUT_LINE('Bom dia!' || ' ' || V_RESULTADO || TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS'));

  FOR RES IN C_AREAS_ATUACOES(1) LOOP
    DBMS_OUTPUT.PUT_LINE('RESULTADO::' || RES.NOME_ATUACAO);
  END LOOP;
END;
